### ISSUE TITLE
Add a "list" procedure to rooms router

### ISSUE THREAD

**Issue by dan2811** [dan2811/yamaha#8]
Similar to your [first task](https://github.com/users/dan2811/projects/4/views/1?visibleFields=%5B%22Title%22%2C%22Assignees%22%2C%22Status%22%2C%22Linked+pull+requests%22%2C%22Repository%22%5D&pane=issue&itemId=72619444) but instead of creating a room we want to list all the rooms.

**Comment by Mariphy** [comment]
It looks like the "list" procedure already exists [here](https://github.com/dan2811/yamaha/blob/4314d79a13de009364d64a1cc2b8b4b4fdfde917/src/server/api/routers/rooms.ts#L7) 
Could you double check that it is complete and the correct procedure?
Can I reuse the "roomsRouter" branch for this. Or is it good practice to create a new branch for each separate issue?

**Comment by dan2811** [comment]
@Mariphy you're absolutely right! Apologies, let's add a "Show" procedure instead that should take a roomId and return all of the details about that room. I'll close this task and create a separate one. 

Best practice is to definitely create a new branch for every task. 😀
